


# --- 拦截 xmlrpc.php ---
location = /xmlrpc.php {
    deny all;
    # 返回 444 断开连接（比 403 更隐蔽）
    return 444;
    # return 403;
}

# 精确匹配：/wp-admin
location = /wp-admin {
    return 403;
}
# 粗暴禁止访问或跳转到/wp-login.php,配置不当的话部分情况会拦住自己人,如有特殊需要,可以临时开放
# (通常正确安装并激活wps-hide-login后不会被此规则拦截,自己人使用约定的入口url可以登录后台)
location = /wp-login.php{
    return 403;
}
# 拒绝非 Google/Bing 爬虫
if ($allow_access = 0) {
    return 444; # 直接断开连接
}
# if ($allowed_bot = 0) {
#     return 403;
# }
# --- 保护 wp-login.php ---
# location = /wp-login.php {
#     limit_req zone=wplogin burst=1 nodelay;

#     # 可选：仅允许特定 IP 登录（推荐！）
#     # allow 192.168.1.100;   # 你的办公 IP
#     # deny all;

#     # 允许 POST（登录提交），但限制频率
#     # try_files $uri =404;
#     # include /etc/nginx/fastcgi_params;
#     # fastcgi_pass php_backend;
#     # fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
# }



# --- 保护 wp-cron.php（可选）---
# 正常应由内部触发，不建议公开访问

location = /wp-cron.php {
    # deny all;  # 如果你用系统 cron 替代
    allow 127.0.0.1;  # 只允许本地或 Cloudflare（谨慎）
    # allow 172.68.0.0/16;  # Cloudflare IP 段（可选）
    deny all;
}

# --- 可选：拦截高频 bot 请求 ---
# location / {
#     limit_req zone=bots nodelay;
#     # 正常流量继续
#     try_files $uri $uri/ /index.php?$args;
# }

# 日志文件控制
location ~* \.(?:ico|css|js|gif|jpe?g|png|ttf|svg|webp)$ {
    access_log off;
    log_not_found off;
    expires 30d;
}
