# com_com.conf
# 引入cf可信ip配置(普通服务器建议定期自动调用更新脚本更新,特殊解析服务器不要使用)
## 适用于cloudflare cdn解析.
include /www/server/nginx/conf/cf-realip.conf;

## 仅当特殊解析服务器才使用下面的方式:
# include real_cdn_ip.conf;

# 自定义日志格式:使用log_format指令定义,第一个参数为name(比如取名为debug_format,main_format),后面是具体的日志格式
include com_log_format.conf;


# 引入白名单国家映射(未必会用到)
include com_country_map.conf;

# 引入蜘蛛或爬虫机器人ua变量映射
include com_ua_map.conf;
# limit_req_zone $binary_remote_addr zone=perip_req:10m rate=1r/s;

# 定义基础限流区域
include com_limit_zone.conf;