# 适用于特殊网站的简化配置(不执行js挑战等高级防护时使用.),作为com_basic.conf的简化版本.

# 自定义特殊日志记录
# 使用变量(比如$server_name)可以为不同网站产生各自的日志文件,如果为了使用fail2ban集中分析可疑恶意请求,则可以集中到同一个可疑日志文件中
access_log /www/wwwlogs/warn.log combined if=$log_warn;
# access_log /www/wwwlogs/$server_name.warn.log combined if=$log_warn;
access_log /www/wwwlogs/all.log main_format_lite ;
access_log /www/wwwlogs/spider.log main_format_lite if=$allow_bot;
# access_log /www/wwwlogs/$server_name.log main_format;



# 匹配所有查询参数中包含"add-to-cart=" 字符串的请求
# 方案1:使用map(总配置http上下文中定义变量$has_add_to_cart)+if
if ($has_add_to_cart) {
    return 403;
}

# ===================== 禁止访问敏感路径 =====================
# 防止路径遍历和双斜杠绕过(多斜杠,由于是正则匹配(包含检查),所以超过2个斜杠也会被命中,无需使用//+或/{2,}匹配)
if ($request_uri ~* "//") {
    return 444;
}
# 防止访问包含敏感关键词的路径
# /wordpress/ 这个路径需要谨慎,部分后台管理页面可能会跳转到包含此字符串的路径
location ~* (wp-login|xmlrpc|wlwmanifest\.xml|SystemConfig|/setup-config\.php) {
    return 444;
    #                 access_log off;
    #                 log_not_found off;
}



# 这里的(/|$)不能写成[/$],这里的$符号在[]中是字面量而非结尾之意
location ~* wp-login|/api(/|$)|/\?author=\d+|/wp-json/wp/v\d+/users {
    deny all;
    return 444;
}

location ~* /\.(git|svn|hg|env|ssh|DS_Store) {
    deny all;
    return 444;
}

# --- 屏蔽数据库/备份文件 ---
location ~* /(dump\.sql|backup(\.sql|\.tar\.gz|\.zip|\.bak)?|database(_backup)?\.sql|schema\.rb) {
    deny all;
    return 444;
}

# --- 屏蔽配置/凭证文件 ---
location ~* /(config(\.json|\.ya?ml|\.php|\.xml)?|secrets?\.json|user_secrets\.yml|production\.json|credentials|id_(rsa|ecdsa|ed25519)|server\.key|\.pem) {
    deny all;
    return 444;
}

# --- 屏蔽开发工具配置 ---
location ~* /(\.vscode|\.idea|sftp\.json|docker-compose\.ya?ml|cloud-config\.ya?ml) {
    deny all;
    return 444;
}

# --- 屏蔽敏感调试接口 ---
location ~* /(phpinfo\.php|server-status|_vti_pvt/service\.pwd) {
    deny all;
    return 444;
}


# 拒绝非 Google/Bing 爬虫
if ($allow_access_ua = 0) {
    return 444; # 直接断开连接
}

# 禁止google访问添加到购物车按钮链接
if ($block_googlebot_cart) {
    return 403;
}
# 禁止CN用户访问(在各个vhost或者共同include的共用com.conf中加入此段)
if ($block_cn = 1) {
    return 444;
}


# 对于无关紧要的请求忽略其日志(典型的/favicon.ico网站图标请求)
location = /favicon.ico {
    access_log off; # 不记录 access log
    log_not_found off; # 即使文件不存在，也不记录 error log
    return 204; # 返回空响应,204 表示请求成功,但无内容

}

