# 定义基础限流区域
# ua限流(使用user-agentl来定义限流区域)
# 针对允许的爬虫的限流区域(酌情调整数值,默认为3)
limit_req_zone $bot_limit_key zone=bot_limit:10m rate=3r/m;
# limit_req_zone $binary_remote_addr zone=ai_limit:10m rate=2r/m;
# 针对普通用户ua的限流
limit_req_zone $user_limit_key zone=user_limit:10m rate=2r/m;

# 其他候选区域
# wp-content/uploads 目录资源限流（比图片更通用，包含所有媒体甚至css文件）
limit_req_zone $binary_remote_addr zone=uploads_limit:10m rate=1r/s;
limit_req_zone $binary_remote_addr zone=img_limit:10m rate=1r/s;


# # 产品页访问限流(基本的笼统限流)🎈
# limit_req_zone $binary_remote_addr zone=product_limit:10m rate=2r/m;


# # 购物车限流(有效性存疑)
# limit_req_zone $binary_remote_addr zone=cart_limit:10m rate=1r/m;
# # post限流区域定义(暂不引用)
# limit_req_zone $binary_remote_addr zone=post_limit:10m rate=10r/m;

# # 全局限流/泛性限流(不针对具体链接类型限流)
# # 慎用,容易引起部分模板首页产品卡片添加购物车无法成功
# # 所有单个ip的请求限流区域(暂时不引用)
# limit_req_zone $binary_remote_addr zone=perip_req:10m rate=30r/s;
# # 定义链接数限流区域
# limit_conn_zone $binary_remote_addr zone=perip_conn:10m;


# 定义限流返回码
limit_req_status 429;
limit_conn_status 429;