# 对图片限流
location ~* ^/wp-content/uploads/.*\.(webp|jpg|png)$ {
    # 针对图片爬虫的专用日志文件(可供配合fail2ban)
    access_log /www/wwwlogs/imgs.log combined;
    # 图片限流
    limit_req zone=img_limit burst=80 nodelay;
    #                 限制下载速度 (KB/s)
    limit_rate 300k;

    #                 缓存优化
    expires 1y;
    add_header Cache-Control "public, immutable";

    #                 静态文件直接返回(检查 $uri（请求路径对应的物理文件）是否存在,存在直接返回,否则404；)
    try_files $uri =404;
}