server
{
    # 注意 username和domain 的替换
    listen 80;
    server_name domain.com www.domain.com;
    index index.php index.html index.htm default.php default.htm default.html;
    
    root /www/wwwroot/username/domain.com/wordpress; 
    
    include /www/server/panel/vhost/nginx/extension/domain.com/*.conf;

    #CUSTOM-CONFIG-START
    include /www/server/nginx/conf/com.conf;
    #CUSTOM-CONFIG-END

    # 用于SSL证书申请时的文件验证相关配置 -- 请勿删除
    include /www/server/panel/vhost/nginx/well-known/domain.com.conf;

    limit_conn perserver 30;
    limit_conn perip 10;
    limit_rate 2048k;

    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    error_page 404 /404.html;

    #SECURITY-START 防盗链配置
    location ~ .*\.(webp|jpg|jpeg|gif|png|js|css)$
    {
        expires 30d;
        access_log /dev/null;
        valid_referers www.domain.com domain.com;
        if ($invalid_referer){
           return 404;
        }
    }

    #SECURITY-END
    include enable-php-74.conf;

    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/domain.com.conf;
    #REWRITE-END

    #禁止访问的文件或目录
    location = /xmlrpc.php {
        deny all;
        return 403;
    }

    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known {
        allow all;
    }

    #禁止在证书验证目录放入敏感文件
    if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" ) {
        return 403;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires 30d;
        error_log /dev/null;
        access_log /dev/null;
    }

    location ~ .*\.(js|css)?$
    {
        expires 12h;
        error_log /dev/null;
        access_log /dev/null;
    }

    access_log  /www/wwwlogs/domain.com.log  main_format ;
    error_log  /www/wwwlogs/domain.com.error.log;
}