# 格式：
# 域名                      后端地址;
#
# 注意：
# 1. 每行末尾必须有分号。
# 2. 后端地址建议写成完整 URL，例如 http://10.10.0.11:80(带上协议和端口可以提供最高的灵活性,允许单项修改,会啰嗦一些)。
# 3. 这里不要写 map { } 外壳，只写映射条目。
# 4. 如果一个根域和所有子域都走同一后端，可以用 .example.com。

# 例如:
# domain-a1-1.com              http://10.10.0.11:80;
# www.domain-a1-1.com          http://10.10.0.11:80;
