
$include /etc/inputrc
set editing-mode emacs

set show-all-if-ambiguous on
set completion-ignore-case on
set search-ignore-case on
set completion-map-case on
set mark-directories on

set visible-stats on


"\e[A": history-search-backward
"\e[B": history-search-forward

set colored-stats on
set colored-completion-prefix on

set menu-complete-display-prefix on

"\C-i": menu-complete
"\e[Z": menu-complete-backward
"\e[3;5~": kill-word
"\C-H": backward-kill-word