# 可以通过bind -f ~/.inputrc的方式激活或重载配置.
#部分环境(老版本bash)下此配置中的某些设置(或者中文注释引起解析错误)导致不生效(导致这个文件不生效!),此时请考虑使用精简版配置()
# 配置生效排查:
# bind -v | grep "变量名"


# ==基础全局设置
$include /etc/inputrc
# 搜索忽略大小写(历史命令搜索) bash 5.3+(readline 8.3+)开始支持(部分readline不支持$if指令)
# $if version >= 8.3
# set search-ignore-case on
# $endif

# 使用emacs编辑模式
set editing-mode emacs
# ==切换到 vi 编辑模式（如果你是键盘侠）
# set editing-mode vi

# 按一下 Tab 就显示所有补全结果
set show-all-if-ambiguous on
# 补全忽略大小写
set completion-ignore-case on
# 输入错误时，按下 Tab 自动更正（类似 Zsh 的模糊匹配）
set completion-map-case on
# 补全目录时自动加上斜杠
set mark-directories on

# 补全列表显示文件类型标识
set visible-stats on


# ==搜索增强 (历史记录快速搜索)
# 输入命令开头再按上下键，只在匹配的历史中搜索
"\e[A": history-search-backward
"\e[B": history-search-forward

# ==颜色与美化 (如果系统支持)
# 补全列表显示颜色
set colored-stats on
# 补全时高亮匹配的部分
set colored-completion-prefix on

# ==快捷键微调(注意shopt的配置不要放在这个文件里，要放在.bashrc或被导入其中)
# 第一次按 Tab 补全共有部分，第二次按才开始循环
set menu-complete-display-prefix on

# 允许按下 Tab 时直接在候选项中循环切换
"\C-i": menu-complete
# 如果你还希望 Shift+Tab 可以反向切换（向后跳）
"\e[Z": menu-complete-backward
# Ctrl+Delete 删除光标后的单词
"\e[3;5~": kill-word
# Ctrl+Backspace 删除光标前的单词
"\C-H": backward-kill-word

# END(下面保留一个空行避免尾部换行符错误)
