sites=(
vieuxsous.com
numis-fr.com
coin-histoire.com
monnaieclub.com
tresor-numis.com
lecoinrar.com 
coinarchivefr.com
coinlegacypro.com
archivede.com
mainstcart.com
easyaisleus.com
dailyfixpro.com
homepulseus.com
livewellcartpro.com
lovelyusshop.com
sweetdailyus.com
operativoshop.com
armesprofr.com
armes-elite.com
waffen24de.com
teutonic-arms.com
tac-vanguard.com
drink-horizon.com
de-winehub.com
globalinkreads.com
shelfwithoutwalls.com
bookzen365.com
readbridgebooks.com
thebookallypro.com
mototrekusa.com
livrezen.com
page-sagesse.com
groove-hub.com
analog-soulfr.com
sonet-disque.com
spin-shop.com
sound-objectpro.com
vinyladdictpro.com
spinritual.com
ecoutevinyle.com
)
base=/www/wwwroot/xcx/s1
#修改用户名
people=cjq

user_dir=$base/$people/deployed
mkdir -p $user_dir/sub
for site in "${sites[@]}"; do
  mv -v $user_dir/"$site"*zst  $user_dir/sub 
done