
#当前用户家目录中常用路径
documents="$home\documents"
downloads = "$home\downloads"
pictures = "$home\pictures"
hosts="$winSystem32\drivers\etc\hosts"
music = "$home\Music\"
videos="$home\videos"
# 文件共享和挂载服务
alist_home="$exes\alist"
chfs_home="$exes\chfs"
aria2_home="$exes\aria2"
# 仓库目录
scripts="$repos\scripts"
configs="$repos\configs"
blogs="$repos\blogs" 
PS="$scripts\PS" 
TaskSchdPwsh="$PS\TaskSchdPwsh"
#其他常用目录

# DF
df="$share\df"
sites="$SystemDrive\sites"
wp_sites="$sites\wp_sites"
my_wp_sites="$desktop\my_wp_sites"

wp_sites_df="$df\wp_sites"
wp_test="$wp_sites\wp.test"
spy_site="$wp_test"
# wp_templates="$wp_sites_df\wp_templates"
# cxxu_templates="$wp_templates\cxxu_templates"

wp_migration="$wp_sites_df\wp_migration"
DF_LocoySpider="$repos\DF_LocoySpider"
phpStarter="$repos\phpStarter"
woocommerce="$DF_LocoySpider\woocommerce"
# woo_df="$woocommerce\woo_df"
woo_df="$scripts\wp\woocommerce\woo_df"
woo_df_server="/repos/scripts/wp/woocommerce/woo_df"
pys="$woo_df\pys"
base_sqls="$wp_sites\base_sqls"
SpiderTeam="$wp_sites\SpiderTeam.ps1"

$SiteOwnersDict=if(test-path $SpiderTeam){. $SpiderTeam}
$DFTableStructure = $SiteOwnersDict.DFTableStructure

wp_plugins="$wp_sites_df\wp_plugins"
reports="$df\reports\cxxu"
phpstudy_extensions="C:\phpstudy_pro\extensions"
