@{
    RootModule = 'Basic.psm1'
    ModuleVersion = '1.0.4'
    GUID = '0cabeabe-fb5c-41a4-b90c-f3d011dec739'
    Author = 'cxxu'
    Description = 'Cxxu PowerShell module: Basic'
    PowerShellVersion = '5.1' # B档兼容集:5.1 可用(其余模块保持 7.0)
    FunctionsToExport = @(
        'Install-SubModules',
        'ls_eza',
        'Restart-TrafficMonitor',
        'Get-Fonts',
        'wiki2latex',
        'ty2latex',
        'wechat_second',
        'startup_register',
        'wechat_multiple',
        'pushToAndroid',
        'downkyi_clickToLaunch',
        'remove_colors_icons',
        'ps_group',
        'rpg',
        'ord',
        'chr',
        'upload_pubKey',
        'BT',
        'colorPicker_vscode',
        'getAssembler_att',
        'getAssemble_intel',
        'Start-ProgramInSandboxie',
        'extract_markdown_titiles',
        'tree_lsd',
        'ld',
        'l1',
        'update_functions',
        'Set-WindowsUpdate',
        'Get-DateTimeNumber',
        'Get-DateTime',
        'Get-Time',
        'remote_folder',
        'Get-LineNumberWidth',
        'Get-ContentNL',
        'Open-AllFiles',
        'New-Junction',
        'u20',
        'vscodeExtListExport',
        'Get-WslInfo',
        'https3w_start',
        'Get-EdgeUpdaterPath',
        'Set-EdgeUpdater',
        'Test-MainPC',
        'Push-ReposesConfiged',
        'Push-ReposesConfigedFromMainPC',
        'New-File',
        'Set-DoubleOwnerOfRepos',
        'Test-CxxuComputer',
        'Update-ReposesConfiged',
        'reboot',
        'timer_tips',
        'Test-IsAdministrator',
        'Test-AdminPermission',
        'Test-AdminPermission2',
        'Set-HostsFile',
        'NetWorkAccessbility',
        'curlBD',
        'pingBD',
        'pingGG',
        'uploadPic',
        'jupyter2markdown',
        'uploadPicMarkdown',
        'Write-SeparatorLine',
        'gcmw',
        'mvToNEEPSub',
        'clock',
        'javav',
        'EnvironmentRequireTips',
        'renamePrefix',
        'search_contents',
        'aliasEdit',
        'mkdirSafeCd',
        'Get-IPAddressMainInfo',
        'Get-IPAddressOfPhysicalAdapter',
        'Get-NetAdapterMainInfo',
        'Restart-Explorer',
        'Restart-Process',
        'pipUpdateIntegration',
        'c',
        'code_proxy',
        'Get-ScriptRootPath',
        'status',
        'time_show',
        'Write-WorkingDir',
        'btm_cxxu',
        'Get-ModuleByCxxu',
        'Get-Utf8Content'
    )
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()
    PrivateData = @{
        PSData = @{
            Tags = @('CxxuPsModules')
            ProjectUri = 'https://github.com/xuchaoxin1375/scripts'
        }
    }
}
